### ISSUE TITLE
Sover panics in special circumstances.

### ISSUE THREAD

**Issue by alexhein** [crillab/gophersat#11]
Hi,
I've seen an error in one case using maxsat (only with solftclauses). I nailed it down to a minimum set of cluauses causing the issue:

	x := maxsat.Var("x")
	hard := maxsat.HardClause(x)
	soft := maxsat.SoftClause(x.Negation())

	problem := maxsat.New(soft, hard)
	problem.Solve()

The error output is:
=== RUN   TestMaxSat
--- FAIL: TestMaxSat (0.00s)
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 18 [running]:
testing.tRunner.func1(0xc42015c0f0)
	/usr/local/go/src/testing/testing.go:742 +0x29d
panic(0x571a60, 0x6879a0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/crillab/gophersat/solver.(*Solver).cleanupBindings(0xc420162000, 0x1)

**Comment by fdelorme** [comment]
Hi,

I'll have a look at that.

**Comment by fdelorme** [comment]
I found the bug. It was a special case that was not being handled in solver.go . Thanks for spotting it, it should be working now (your minimum test above passes).
