### ISSUE TITLE
Interpretation of bf.And() and bf.Or()

### ISSUE THREAD

**Issue by highmtworks** [crillab/gophersat#16]
The tests below fail:
```
func TestIdentityAnd(t *testing.T) {
	f1 := bf.And(bf.And(bf.Var("x")))
	f2 := bf.And(bf.And(), bf.And(bf.Var("x")))
	m := map[string]bool{"x": true}
	if f1.Eval(m) != f2.Eval(m) {
		t.Fail()
	}
}
```

```
func TestIdentityOr(t *testing.T) {
	f1 := bf.Or(bf.Or(bf.Var("x")))
	f2 := bf.Or(bf.Or(), bf.Or(bf.Var("x")))
	m := map[string]bool{"x": false}
	if f1.Eval(m) != f2.Eval(m) {
		t.Fail()
	}
}
```

Are these expected ?

As
`and(and(x), and(y))` == `and(and(x, y))`
`or(or(x), or(y))` == `or(or(x, y))`
hold,
it may be happy if the following also hold:
`and(and(), and(x))` == `and(and(x))`
`or(or(), or(x))` == `or(or(x))`

For example, emacs lisp returns `t` for `(and)`, and `nil` for `(or)` .

**Comment by fdelorme** [comment]
First, sorry for the very long delay, I hadn't been notified of issues on my e-mail.

Yes, `and()` should be true, and `or()` should be false, so your tests should succeed. I'll have a look at it.
