### ISSUE TITLE
would be good to put these test files into the repo instead of living in some home dir

### ISSUE THREAD

**Issue by scottstensland** [crillab/gophersat#2]
getting errors when running  `go test`

<details>
<summary>solver_test.go:17: open /Users/delorme/prog/sat/25.cnf: no such file or directory 
</summary>

stens@cameroon ~/src/gopath/src/github.com/crillab/gophersat/solver $ go test
c ======================================================================================
c ======================================================================================
c ======================================================================================
c ======================================================================================
c ======================================================================================
--- FAIL: TestSolver (0.00s)
	solver_test.go:17: open /Users/delorme/prog/sat/25.cnf: no such file or directory
	solver_test.go:17: open /Users/delorme/prog/sat/50.cnf: no such file or directory
	solver_test.go:17: open /Users/delorme/prog/sat/75.cnf: no such file or directory
	solver_test.go:17: open /Users/delorme/prog/sat/100.cnf: no such file or directory
	solver_test.go:17: open /Users/delorme/prog/sat/125.cnf: no such file or directory
	solver_test.go:26: Invalid result for "/Users/delorme/prog/sat/125.cnf": expected 2, got 1
c ======================================================================================
c ======================================================================================
c | Restarts |  Conflicts  |  Learned  |  Deleted  | Del% | Reduce |   Units learned   |
c | Restarts |  Conflicts  |  Learned  |  Deleted  | Del% | Reduce |   Units learned   |
c ======================================================================================
c ======================================================================================
FAIL
c ======================================================================================
exit status 1
FAIL	github.com/crillab/gophersat/solver	0.001s

</details>

**Comment by fdelorme** [comment]
Thanks. This has been fixed.
