### ISSUE TITLE
Access to maxsat.Problem.solver

### ISSUE THREAD

**Issue by sten13** [crillab/gophersat#21]
I am constructing a MAXSAT problem programmatically (i.e., not through ParseWCNF) and would now like to access the solver in maxsat.Problem. But that component is not exported. Could you export that field or otherwise give access to the solver?

**Comment by sten13** [comment]
I am currently making do with the following code in `maxsat/problem.go`:

```
// Solver returns the solver associated with this problem.
func (pb *Problem) Solver() *solver.Solver {
       return pb.solver
}
```

**Comment by fdelorme** [comment]
This is done. Please let me know if I can close the issue now.

**Comment by sten13** [comment]
Yep, I've removed my local changes, updated the repo and rebuilt my software. Works. Thanks!
