### ISSUE TITLE
hello world sat

### ISSUE THREAD

**Issue by ronaldpetty** [crillab/gophersat#3]
Hi,

I am interested in spinning the wheels with gophersat.  Just curious, is there a standard 'hello world' type problem that only SAT easily solves?  If so, can you point me to one and I will try to learn enough to convert to Go (as a driver) and solve with gophersat.  Then will do a PR so we have an example here.

Thanks for the project.

Ron

**Comment by fdelorme** [comment]
Hello,

I have just added the description of a few toy examples in the `examples` directory : how to make a sudoku solver and a timetable generator. Other examples will come. Adding code that implements these examples would be cool, yes.

Fabien

**Comment by ronaldpetty** [comment]
Sweet, will dive in, thanks again!
