### ISSUE TITLE
gometalinter issues

### ISSUE THREAD

**Issue by dgryski** [crillab/gophersat#6]
Running [gometalinter](https://github.com/alecthomas/gometalinter) across the repo brings up a few issues, most of which are cosmetic, but it does flag the following which does look like a real bug:

```
solver/watcher.go:309:5:warning: ineffective break statement. Did you mean to break out of the outer loop? (SA4011) (megacheck)
solver/watcher.go:317:5:warning: ineffective break statement. Did you mean to break out of the outer loop? (SA4011) (megacheck)
```

**Comment by fdelorme** [comment]
Thank you Damian!

Yep, that was a bug, not the kind that produces wrong results, but the kind leading to useless computations.

This is fixed now.

**Comment by dgryski** [comment]
Were you keeping this open to address the other lint finds or can this be closed?

**Comment by fdelorme** [comment]
Yes, it can be closed, I'll check other linter messages but they all seem to be cosmetic problems.
