### ISSUE TITLE
undefined: solver.ParsePBConstrs

### ISSUE THREAD

**Issue by sciolizer** [crillab/gophersat#7]
I might be missing something obvious, but a vanilla install fails for me:

```
➜  ~ go get github.com/crillab/gophersat
# github.com/crillab/gophersat/maxsat
go/src/github.com/crillab/gophersat/maxsat/problem.go:62:10: undefined: solver.ParsePBConstrs
```

Possibly related to https://github.com/crillab/gophersat/commit/9b32be33d3396a0e749dab31bffa0a0593c5b074

**Comment by wsc1** [comment]
ditto

**Comment by fdelorme** [comment]
Hello @sciolizer and @wsc1, sorry, I hadn't seen your issue until these last days. This is now fixed.
