### ISSUE TITLE
Incorrect number of models after creating problem with ParseSlice

### ISSUE THREAD

**Issue by k-toffel** [crillab/gophersat#8]
Hey,
first of all I'm actually not that familiar with the field of SAT solving and solvers, therefore I hope that I don't waste your time.

I have a small assignment of converting the problem of solving a game of Unruly into a SAT instance. Which has all worked pretty nice and the models I get are all correct.

My problem rises when I want to get the number of possible solutions/models. I know for a fact that all the puzzles have exactly one solution and also double checked that using `PicoSat 965`. For this I created a valid CNF file. Using this file also yields the correct result when using `gophersat`, but as soon as I want to use `ParseSlice` in order to avoid creating the cnf string, writing it to a file and reading it immediately afterwards I get incorrect results.

I had a look at the code and realized that instead of calling `simplify2` like `ParseCNF` does (when reading from a .cnf file) `ParseSlice` calls `simplify`. As far as I can tell `simplify` runs an UP just like `simplify2`. Therefore I changed the call in `ParseSlice` to `simplify2` and voilà it works.

As I said I'm not that familiar with SAT solvers and am not sure wether this will break something else down the road.

Unfortunately I wasn't able to find a simple example to reproduce this behaviour and it only occurs when I test the biggest games provided (32x32 fields). Hence the resulting cnf file and slice of a slice of ints are pretty big. That's why I'm not posting these files yet..

Have a good one

**Comment by fdelorme** [comment]
Hello,

I just saw this issue was pending! This is a very old one, and you were totally right. I just fixed it, as it should have been months ago.

Thank you very much and sorry for the delay.

Fabien
